### ISSUE TITLE
Login got changed to Connection in php-twinfield dependency

### ISSUE THREAD

**Issue by Waterdhavian** [willemo/laravel-twinfield#1]
The existing Login class is no longer used by php-twinfield.
We need to change this to the Connection class.

**Comment by Waterdhavian** [comment]
I have fixed the issue but i cannot make a pull request. I am new to Github in terms of contributing. No matter what i select when creating a pull request. The create pull request button stays grayed out.

**Comment by willemo** [comment]
Hi @Waterdhavian, thanks for letting me know, I was aware that the supported logins were deprecated, but I was hoping they would be working a bit longer.

To make a pull request you first have to fork this repository by clicking the Fork button above. This will create a copy to your own GitHub account. You can then clone it/check it out to your local computer and modify the code (preferably in a new branch). After that's done, you commit the changes and push the code back to GitHub. Then you can use the GitHub website to create a pull request for your code.

**Comment by Waterdhavian** [comment]
Hey @willemo 

Yeah i know you were aware, since you were the author of the change haha ;)
I wanted to save you some time and fix it for this repo. 

Thanks for pointing that out.

Going to give that a try now.

**Comment by willemo** [comment]
Thanks for the fix! I've merged it!

**Comment by Waterdhavian** [comment]
You are welcome, i just noticed that you are not same author as the Willem who works on php-twinfield, haha! My bad!

**Comment by willemo** [comment]
No worries ;-)
