### ISSUE TITLE
How to use oauth

### ISSUE THREAD

**Issue by jhjvandenbroek** [willemo/laravel-twinfield#6]
How to use the OAuth flow? I get the following error message

```
PhpTwinfield\Exception: Failed logging in using the credentials, result was &quot;Invalid&quot;. in file /var/www/html/vendor/php-twinfield/twinfield/src/Services/SessionService.php on line 48
--
.... trace info ....
```
I expected it to ignore credentials and use the client ID/secret instead.

I attempt to use the API with this test code:
```
class TestTwinfieldController
{
    public function index() {
        $customerApiConnector = Twinfield::get('Customer');
        // Get a list of all customers.
        $office   = Office::fromCode('NLAXXXXXX');
        $customer = $customerApiConnector->listAll($office);
        dd($customer);
    }
}
```
My .env looks something like this:
```
TWINFIELD_USERNAME=
TWINFIELD_PASSWORD=
TWINFIELD_AUTH_TYPE=oauth
TWINFIELD_CLIENT_ID=myclientId
TWINFIELD_CLIENT_SECRET=myclientSecret
TWINFIELD_RETURN_URL=http://localhost/dashboard/oauthCallback
TWINFIELD_ORGANISATION=NLAXXXXXX
TWINFIELD_OFFICE=CompanyName
```

**Comment by willemo** [comment]
Hi, I see that the OAuth flow hasn't been implemented yet. I haven't used this package for quite a while, so it wasn't on my radar.

I'm open to PRs for this. The solution can be built into [`ApiConnectorFactory`](https://github.com/willemo/laravel-twinfield/blob/master/src/Factories/ApiConnectorFactory.php#L57), the method for fetching the authentication method should be expanded to include an option for the OAuth flow, depending on the configuration file.

**Comment by jhjvandenbroek** [comment]
That's unfortunate. Thx for letting me know. Could be interesting to contribute this way. However at this moment I don't have the time.
